version: '2'

services:
  repopreview:
    container_name: repopreview
    build: .
    environment:
      - REPOPREVIEW__GITHUB__API_KEY=${REPOPREVIEW__GITHUB__API_KEY}
    ports:
      - "8080:8080"

  nginx:
    container_name: nginx
    image: nginx:1.13
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./cert.pem:/etc/nginx/ssl/cert.pem
      - ./ssl.key:/etc/nginx/ssl/ssl.key
      - ./dhparam.pem:/etc/nginx/ssl/dhparam.pem
      - ./.well-known/:/app/.well-known/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - repopreview
