version: '2.1'

services:
  repopreview:
    container_name: repopreview
    build: .
    environment:
      - REPOPREVIEW__GITHUB__API_KEY=${REPOPREVIEW__GITHUB__API_KEY}
    ports:
      - "8080:8080"
